version: "3.8"

services:
  db:
    image: mysql:8
    container_name: vending-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vending
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  server:
    build: ./server
    container_name: vending-server
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  pi-agent:
    build: ./client
    container_name: vending-pi
    ports:
      - "5000:5000"